export const RULES = {
  "401": { label: "Pa.R.E. 401", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter4/s401.html" },
  "403": { label: "Pa.R.E. 403", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter4/s403.html" },
  "408": { label: "Pa.R.E. 408", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter4/s408.html" },
  "602": { label: "Pa.R.E. 602", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter6/s602.html" },
  "701": { label: "Pa.R.E. 701", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter7/.html" },
  "702": { label: "Pa.R.E. 702", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter7/s702.html" },
  "801": { label: "Pa.R.E. 801", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter8/s801.html" },
  "8036": { label: "Pa.R.E. 803(6)", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter8/s803-6.html" },
  "901": { label: "Pa.R.E. 901", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter9/s901.html" },
  "1002": { label: "Pa.R.E. 1002", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter10/s1002.html" },
  "1003": { label: "Pa.R.E. 1003", url: "https://www.pacodeandbulletin.gov/secure/pacode/data/225/chapter10/s1003.html" }
};

function evidence(evidenceType, label, offeredToProve, evidenceIssue, foundation, legalReason, paralegalTask, ruleKey) {
  const rules = (Array.isArray(ruleKey) ? ruleKey : [ruleKey]).map((key) => RULES[key]);
  return {
    evidenceType,
    evidence: label,
    offeredToProve,
    evidenceIssue,
    foundation,
    legalReason,
    paralegalTask,
    rules,
    ruleReference: rules[0].label,
    ruleUrl: rules[0].url,
    questionToConsider: `What foundation or objection matters when this item is offered to prove ${offeredToProve.toLowerCase()}?`
  };
}

const RAW_CASE_INSTRUCTION = [
  {
    slug: "blue-tile",
    claim: "Vale Apartments claims that the contractor installed tile that did not comply with the written change order. The contractor says the building manager approved the blue substitution before installation.",
    disputedIssue: "Was the change from green tile to blue tile authorized?",
    evidenceFocus: "Relevance and authentication",
    ruleCard: {
      title: "Relevance and authentication",
      plain: "Evidence is relevant when it tends to make an important fact more or less probable. Authentication separately requires enough support for a finding that an item is what its proponent claims.",
      simplified: "A project item matters here only if it helps prove authorization, timing, or performance. A witness, distinctive features, or reliable records may supply authentication, but authentication does not resolve every other objection.",
      rules: [RULES["401"], RULES["901"]]
    },
    paralegalPractice: "Preserve original project files, identify a witness for each exhibit, and record where each item came from.",
    discussionQuestion: "What additional foundation would be needed if the source of the building manager's text were disputed?",
    debrief: "The most useful items connected the color substitution to authorization and could be identified by a witness or reliable project record.",
    examples: [2, 4],
    caseRoles: ["Contract signatory", "Project architect", "Vendor records custodian", "Photograph witness", "Building manager", "Contractor", "Delivery driver", "Project scheduler", "Tile installer", "Billing clerk", "Meeting note-taker", "Project manager", "Security system custodian", "Project architect", "Vendor records custodian", "Building manager deponent"],
    items: [
      evidence("contract", "Signed construction contract", "the original renovation scope", "Relevance and authentication", "A signer or project custodian identifies the executed agreement", "the signed agreement directly defined the promised work and a signer identified it", "Compare the executed copy with the client file and add the signer to the witness list", ["401", "901"]),
      evidence("plan", "Original tile specification", "the required tile color and model", "Authentication", "The architect or specification custodian identifies the final specification", "the file lacked a date and no witness could distinguish it from superseded drafts", "Locate the native file, revision history, and a witness who used the specification", "901"),
      evidence("contract", "Revised purchase order", "when blue tile was ordered", "Relevance and authentication", "The vendor's custodian or project accountant identifies the order", "the dated order made authorization timing more probable and its custodian identified it", "Preserve the vendor copy and document the order number and collection source", ["401", "901"]),
      evidence("photograph", "Photograph of installed tile", "the color and condition after installation", "Authentication", "A witness who saw the hallway confirms the image fairly depicts it", "a witness with personal knowledge confirmed what the image depicted and when", "Keep the original image file and record who supplied and identified it", "901"),
      evidence("text", "Manager's text message", "approval of the blue substitution", "Digital authentication", "The recipient must identify the thread and connect it to the manager", "the cropped screenshot omitted account details and no participant identified it", "Export the full thread with dates, participants, and collection notes", "901"),
      evidence("voicemail", "Contractor's voicemail", "the contractor's understanding before installation", "Voice identification", "A listener familiar with the contractor's voice identifies the speaker", "no witness identified the voice and the isolated audio contained no reliable identifying context", "Retain the original audio and locate a witness familiar with the speaker's voice", "901"),
      evidence("receipt", "Tile delivery receipt", "the date blue tile reached the property", "Relevance and authentication", "The driver or vendor record custodian identifies the receipt", "the receipt helped establish timing and was connected to the delivery by a knowledgeable witness", "Match the receipt to the purchase order and note the proposed foundation witness", ["401", "901"]),
      evidence("spreadsheet", "Project timeline", "the planned approval and installation dates", "Authentication", "The project scheduler explains who created and maintained it", "the exhibit was an undated reconstruction prepared for suit, with no witness able to explain its source", "Obtain the native schedule, metadata, and testimony about when it was maintained", "901"),
      evidence("object", "Physical blue tile sample", "the material actually installed", "Identification and chain of custody", "The contractor identifies where and when the sample was removed", "the removal witness marked and identified the sample as coming from the hallway", "Label the sample, photograph it, and maintain a simple custody log", "901"),
      evidence("receipt", "Final invoice", "the material billed to Vale Apartments", "Authentication and foundation", "The contractor's billing custodian would need to identify the invoice", "the page mixed charges from several jobs and no billing witness tied the blue tile line to Vale", "Compare the invoice to payment records and prepare the billing custodian", "901"),
      evidence("note", "Weekly meeting notes", "whether anyone discussed the color change", "Authentication", "The note-taker identifies the notes and meeting", "the pages omitted the meeting date and author, leaving their identity unsupported", "Identify the note-taker and preserve the complete notebook rather than selected pages", "901"),
      evidence("contract", "Unsigned change-order form", "that a blue substitution was proposed before installation", "Foundation and relevance", "A project witness identifies the circulated proposal and its date", "a project witness authenticated the circulated proposal; its lack of a signature affected weight, not its limited relevance", "Trace the draft through email and document whether it was ever sent or accepted", ["401", "901"]),
      evidence("recording", "Lobby surveillance recording", "the installation date", "System authentication", "A system witness must explain the camera and export process", "the clip showed a reset clock and no witness explained the system or established the actual date", "Preserve the native export and document the camera, time setting, and hash value", "901"),
      evidence("plan", "Architect's revision drawing", "the design approved before installation", "Relevance and authentication", "The architect identifies the revision block and issued drawing", "the issued drawing bore a revision date and was identified by its author", "Collect the full drawing set and confirm the revision history", "901"),
      evidence("spreadsheet", "Vendor color spreadsheet", "which color code was reserved for the Vale order", "Relevance and authentication", "The vendor identifies the dated sheet and project code", "the authenticated sheet tied the blue product code to Vale's reserved order before installation", "Preserve the native sheet and document the project and color codes", ["401", "901"]),
      evidence("transcript", "Manager's deposition excerpt", "the manager's account of approval", "Completeness and purpose", "The certified transcript and relevant surrounding pages identify the testimony", "the isolated excerpt omitted the question and qualification needed to understand the answer", "Designate complete pages and check the transcript against the reporter's certification", "401")
    ]
  },
  {
    slug: "garden-goose",
    claim: "Two neighboring households each claim that a twelve-foot floral goose was promised for their garden during the spring tour. One seeks return of the display and the other seeks reimbursement for planting costs.",
    disputedIssue: "Which garden was the display intended to occupy?",
    evidenceFocus: "Authentication of photographs and physical evidence",
    ruleCard: {
      title: "Showing an item is what it claims to be",
      plain: "Authentication requires enough evidence to support a finding that an exhibit is genuine. The rule gives examples, not a single required method.",
      simplified: "A photograph may be authenticated by someone who observed what it depicts; the photographer is not always required. A physical item may be identified through testimony, markings, or a documented chain of custody.",
      rules: [RULES["901"]]
    },
    paralegalPractice: "Keep original image files, photograph physical exhibits with identifying markers, and prepare a source and custody log.",
    discussionQuestion: "Could a neighbor who did not take a photograph still authenticate what it depicts? What would that witness need to know?",
    debrief: "Images and objects became useful only when the case facts connected them to the correct garden, date, or display.",
    examples: [1, 8],
    caseRoles: ["Neighbor witness", "Gardener", "Display artist", "Tour organizer", "Garden owner", "Social media account holder", "Display artist", "Device owner", "Tour coordinator", "Volunteer coordinator", "Grounds volunteer", "Garden witness", "Display artist", "Route volunteer", "Cart renter", "Brochure designer"],
    items: [
      evidence("photograph", "Wide garden photograph", "the goose's placement before the tour", "Photograph authentication", "A neighbor who saw the garden confirms the image accurately depicts it", "the witness could not say which year the similar-looking photograph showed", "Preserve metadata and identify a witness who saw the scene on the relevant date", "901"),
      evidence("photograph", "Phone photo with flower beds", "the display beside the north garden", "Photograph authentication", "The gardener who observed the scene identifies the location and date", "a witness with firsthand knowledge confirmed the scene and timing", "Export the original image and record the witness's basis of knowledge", "901"),
      evidence("object", "Painted wooden wing", "that the recovered piece came from the disputed goose", "Physical identification", "The artist identifies a unique repair mark on the wing", "the artist identified a distinctive repair that connected the wing to the display", "Photograph the repair mark and maintain the exhibit label and custody history", "901"),
      evidence("map", "Tour organizer's plot map", "the assigned garden location", "Authentication", "The organizer identifies the final map distributed to volunteers", "no witness could distinguish the sheet from several preliminary layouts", "Collect all versions and identify the final approved map", "901"),
      evidence("receipt", "Seedling purchase receipt", "planting expenses claimed as damages", "Relevance and authentication", "The buyer and shop record identify the transaction", "the dated purchase was tied to the claimed preparation costs", "Match the receipt to payment proof and damages calculations", "901"),
      evidence("photograph", "Cropped social-media image", "the display's location", "Authentication and completeness", "A witness identifies the uncropped source and location", "the crop removed landmarks and no source file or knowledgeable witness was supplied", "Request the original post and uncropped file with account information", "901"),
      evidence("note", "Artist's paint notation", "the color pattern of the commissioned goose", "Handwriting identification", "The artist would need to identify the note and matching paint codes", "the unsigned loose page was not connected to the artist or this display", "Collect a clean scan and photograph the corresponding paint areas", "901"),
      evidence("recording", "Doorbell-camera clip", "who moved the goose before dawn", "Digital authentication", "The homeowner explains the camera, corrected timestamp, and export", "the homeowner explained the clock correction and preserved footage showing the move", "Document device settings and preserve the native clip and surrounding footage", "901"),
      evidence("object", "Numbered planting stake", "the plot assigned to the display", "Physical identification", "The tour coordinator identifies the numbering system", "the coordinator connected the marked stake to the official plot assignment", "Bag and label the stake and photograph it in place before moving it", "901"),
      evidence("email", "Volunteer placement email", "the location volunteers were told to use", "Digital authentication", "The sender identifies the message and recipient list", "the sender and full thread connected the instruction to the tour plan", "Save the native message with headers and attachment list", "901"),
      evidence("object", "Loose artificial feather", "that the goose passed through the south gate", "Connection to the dispute", "A witness explains collection and a distinctive match", "the generic feather had no distinctive feature or documented collection location", "Record collection location immediately and avoid overstating an uncertain match", "901"),
      evidence("photograph", "Printed instant-camera photo", "the goose beside the hedge", "Photograph authentication", "A person present would need to identify the scene and date", "no witness could place the unlabeled print at either garden on the relevant day", "Identify the observing witness and scan both sides of the print", "901"),
      evidence("contract", "Display loan tag", "the intended borrower and return date", "Authentication", "The artist identifies the tag attached before delivery", "the artist identified the tag and its attachment to the display", "Photograph the tag in place and preserve its string and markings", "901"),
      evidence("map", "Hand-drawn shortcut sketch", "the route used to move the display", "Authentication", "The alleged author or recipient identifies the sketch", "neither the author nor recipient could be identified from the anonymous sketch", "Trace the sketch's source before listing it as a proposed exhibit", "901"),
      evidence("receipt", "Garden cart rental receipt", "when equipment was obtained to move the goose", "Relevance", "The renter or rental custodian must connect the transaction to the move", "the generic receipt named no renter, garden, or display and did not connect the cart to this move", "Confirm the renter, pickup time, and relation to the claimed move", "901"),
      evidence("photograph", "Tour brochure cover image", "the planned display location", "Relevance and authentication", "The designer identifies the cover as based on the final approved placement", "the designer connected the cover image to the final placement plan and identified its landmarks", "Interview the designer before treating promotional artwork as a factual record", "401")
    ]
  },
  {
    slug: "wandering-clock",
    claim: "Two buyers each claim ownership of an ornate clock sold during a community attic sale. One relies on a signed sales sheet; the other relies on a later duplicate receipt and pickup arrangements.",
    disputedIssue: "Which transaction transferred ownership of the clock?",
    evidenceFocus: "Contracts, writings, originals, and duplicates",
    ruleCard: {
      title: "Originals and duplicates",
      plain: "When a party seeks to prove the content of a writing, recording, or photograph, the original is generally required unless another rule applies. An accurate duplicate is ordinarily admissible to the same extent as the original.",
      simplified: "A copy is not excluded merely because it is a copy. In this case, a duplicate is accepted unless a genuine authenticity question or unfairness makes the original important.",
      rules: [RULES["1002"], RULES["1003"]]
    },
    paralegalPractice: "Locate originals, compare duplicates, note any alterations, and organize writings by transaction date.",
    discussionQuestion: "What fact would make production of the original sales sheet especially important?",
    debrief: "The writings mattered because their contents defined the competing sales. Accurate duplicates remained usable unless authenticity or fairness required the original.",
    examples: [0, 6],
    caseRoles: ["Clock seller", "Shop records custodian", "Pickup witness", "Inventory clerk", "Email recipient", "Clock seller", "Payment clerk", "Prospective buyer", "Clock owner", "Pickup coordinator", "Buyer", "Auction records custodian", "Clock restorer", "Payment system custodian", "Attic-sale volunteer", "Auction-house custodian"],
    items: [
      evidence("contract", "Signed first-sale sheet", "the first buyer's agreement and price", "Original writing and authentication", "The seller and buyer identify the executed sheet", "the original signed writing directly recorded the first transaction", "Sleeve the original, scan both sides, and record who produced it", ["1002", "901"]),
      evidence("receipt", "Duplicate second-sale receipt", "the later buyer's payment", "Admissibility of duplicates", "The shop's system and seller identify the accurate duplicate", "the accurate system duplicate was admissible without a genuine authenticity dispute", "Compare the duplicate to the transaction log and retain the export method", "1003"),
      evidence("photograph", "Photo of clock at first pickup", "possession after the first sale", "Relevance and authentication", "A witness present identifies the scene and date", "no witness or metadata connected the image to the relevant date", "Obtain the original file and identify someone who observed the pickup", "901"),
      evidence("note", "Seller's inventory card", "the clock's item number and status", "Original writing and authentication", "The seller would need to identify which version was kept with the clock", "the overwritten card had no date and the seller could not identify when its status changed", "Photograph the card with the clock and preserve both sides", ["1002", "901"]),
      evidence("email", "Pickup confirmation email", "the agreed pickup time", "Digital writing and authentication", "The recipient identifies the complete thread", "the complete authenticated thread showed the parties' performance arrangements", "Save the native email and headers with the attachment list", "901"),
      evidence("contract", "Unsigned sales draft", "proposed terms with the second buyer", "Relevance and completeness", "A party explains its draft status", "the unsigned draft did not establish acceptance and no surrounding communication supplied it", "Link drafts to the messages that show whether terms were accepted", "401"),
      evidence("receipt", "Carbon-copy deposit slip", "the first buyer's deposit", "Duplicate", "The seller identifies the carbon copy made with the original", "the contemporaneous carbon copy accurately reproduced the original deposit record", "Compare copy identifiers and place it beside the payment ledger", "1003"),
      evidence("text", "Text containing revised price", "a proposed price change", "Purpose and completeness", "The sender or recipient identifies the full exchange", "the isolated screenshot omitted the response and could not prove agreement", "Collect the entire thread and identify proposal and acceptance separately", "901"),
      evidence("contract", "Photocopy of warranty", "the clock's serial number", "Duplicate and authenticity", "The repair shop would need to confirm that the copy accurately reproduces its record", "the blurred serial number created a genuine authenticity question and the available original was not produced", "Compare the number to the clock and photograph the serial plate", "1003"),
      evidence("note", "Handwritten pickup list", "the order in which buyers were called", "Authentication", "The volunteer who wrote the list identifies it", "the writer identified the list and explained when it was used", "Interview the writer and preserve the full page with adjacent entries", "901"),
      evidence("recording", "Voicemail accepting a price", "whether a buyer accepted the offer", "Recording content and voice identification", "A familiar listener identifies the voice and original recording", "the identified recording contained words of acceptance relevant to contract formation", "Preserve the original audio and document voice-identification testimony", ["1002", "901"]),
      evidence("contract", "Typed ownership certificate", "the clock's claimed prior owner", "Authentication", "The auction-house records custodian identifies the issued certificate", "the records custodian authenticated the certificate and matched its item number to the clock", "Trace the issuer and compare the document with maintained records", "901"),
      evidence("photograph", "Scanned maker's label", "the identity of the particular clock", "Duplicate photograph", "A witness would need to compare the scan with the label still on the clock", "the scan cropped the identifying digits and no witness confirmed it accurately reproduced the label", "Capture a new color image with scale and note who performed the comparison", "1003"),
      evidence("spreadsheet", "Sale-day payment export", "the time and amount of electronic payment", "Electronic original", "The system custodian would need to explain the data and export query", "the unexplained spreadsheet omitted account identifiers and no custodian connected it to the payment system", "Preserve the native export and document the query used to create it", "1002"),
      evidence("note", "Price tag found in a drawer", "the asking price", "Connection to item", "A witness connects the tag to this clock", "nothing on the loose tag tied it to the disputed clock", "Photograph tags in place before separation and record identifying marks", "901"),
      evidence("contract", "Certified auction-house copy", "an earlier transfer in the ownership chain", "Copy of record", "The auction house certification identifies its maintained record", "the certified record helped establish the clock's ownership history", "Verify the certification and organize the chain of title chronologically", "1003")
    ]
  },
  {
    slug: "lantern-festival",
    claim: "Riverbend Festival Association seeks return of a catering deposit after rain canceled the lantern festival. The caterer says the organizer confirmed that food service would proceed indoors.",
    disputedIssue: "Did the parties confirm indoor service before cancellation?",
    evidenceFocus: "Emails, text messages, and digital evidence",
    ruleCard: {
      title: "Digital evidence needs a connection",
      plain: "Digital evidence must be connected to the person or entity claimed. Contents, account details, witnesses, metadata, and reliable processes may contribute to that showing.",
      simplified: "A printout alone does not authenticate an email or text. This case treats a message as authenticated only when the facts identify its participants and preserve enough context to evaluate it.",
      rules: [RULES["901"]]
    },
    paralegalPractice: "Collect complete native threads, preserve headers and attachments, and record the account, device, and person from whom each export came.",
    discussionQuestion: "Which details in a message thread help connect a digital statement to its claimed sender?",
    debrief: "Complete threads, account information, and knowledgeable witnesses made digital communications usable. Printing a message did not do that by itself.",
    examples: [1, 10],
    caseRoles: ["Festival organizer", "Caterer", "Email recipient", "Venue network administrator", "Weather-alert recipient", "Text participant", "Digital evidence technician", "Voice-note recipient", "Task-board administrator", "Seating coordinator", "Forensic examiner", "Festival organizer", "Device owner", "Cloud system administrator", "Festival organizer", "Volunteer chat participant"],
    items: [
      evidence("email", "Organizer's full email thread", "whether indoor service was approved", "Digital authentication", "A participant must identify the accounts, thread, and attached floor plan", "no participant identified the exported account names and the native headers were missing", "Export the message with full headers and every attachment", "901"),
      evidence("text", "Caterer's group-text export", "the service plan shared with staff", "Digital authentication", "A participant identifies the group and surrounding messages", "the participant and full sequence supplied identity and context", "Record participants and preserve the native export from the device", "901"),
      evidence("email", "Printed cancellation email", "when cancellation notice was sent", "Authentication", "The sender or recipient identifies the message and account", "the printout had no headers and neither sender nor recipient identified it", "Obtain the native email rather than relying on a paper printout", "901"),
      evidence("recording", "Venue Wi-Fi login record", "that an organizer's assigned device reached the hall", "System authentication and relevance", "The network custodian explains logging and a badge record connects the device to the organizer", "the combined device assignment and system foundation made the organizer's timely presence more probable", "Link device identifiers to a custodian before drawing conclusions", ["401", "901"]),
      evidence("photograph", "Screenshot of weather alert", "the timing of the storm warning", "Authentication and relevance", "The person who captured it identifies source and time", "the identified screenshot helped place the warning before the final confirmation", "Record the source application, capture time, and original file", "901"),
      evidence("text", "Single cropped text bubble", "that the recipient received the phrase 'go ahead'", "Limited purpose and authentication", "The recipient identifies the exact message and exporting device", "the participant authenticated the bubble for the limited fact that those words were received, not what an omitted proposal meant", "Collect messages before and after the excerpt and identify the exporting device", "901"),
      evidence("email", "Catering attachment metadata", "when the indoor menu was added", "Process authentication", "A technician or custodian must explain the metadata extraction", "no witness explained the extraction method or whether the displayed time changed during export", "Save the native file and document the extraction tool and operator", "901"),
      evidence("recording", "Voice-note confirmation", "the caterer's understanding of the plan", "Voice and file authentication", "A recipient would need to identify the voice and original chat thread", "the isolated audio was detached from its chat and no familiar listener identified the speaker", "Export the voice note with its surrounding chat and file metadata", "901"),
      evidence("spreadsheet", "Shared task-board export", "assigned indoor setup tasks", "System authentication", "The platform custodian or users explain accounts and timestamps", "no witness explained whether timestamps reflected creation, editing, or export", "Document platform behavior and obtain audit history where available", "901"),
      evidence("email", "Reply-all seating diagram", "that indoor seating was circulated", "Digital authentication", "Recipients identify the sender, attachment, and thread", "the authenticated circulation supported that indoor planning continued", "Preserve recipient headers and the exact diagram version", "901"),
      evidence("text", "Organizer's phone extraction", "the complete sequence of confirmations", "Process and identity", "A qualified witness must explain the extraction and account identifiers", "the report omitted its hash comparison and did not identify the device or extraction operator", "Retain the extraction report, hash value, and device custody notes", "901"),
      evidence("email", "Forwarded vendor message", "that the organizer received a warning from the forwarder", "Notice rather than truth", "The organizer identifies the received forward and its account", "the authenticated forward was admitted only to show notice to the organizer, not to prove the vendor's embedded assertion", "Obtain the original message from its sender or account custodian", ["801", "901"]),
      evidence("map", "Location-history screenshot", "the caterer's arrival at the venue", "Authentication and relevance", "The device owner and system information connect the record to the person", "the identified device record made timely arrival more probable", "Preserve the export settings and confirm who possessed the device", "901"),
      evidence("receipt", "Cloud-storage audit receipt", "when the contract folder was accessed", "System authentication", "The administrator must connect the shared account to a particular user", "the shared login record did not identify which person accessed the folder", "Export the full audit range and document account ownership", "901"),
      evidence("email", "Draft email in unsent folder", "the organizer's plan before cancellation", "Limited relevance and authorship", "The account owner identifies authorship, timing, and draft status", "the identified draft was admitted only as circumstantial evidence of the organizer's plan, not as communicated approval", "Separate drafts from sent messages in the chronology", ["401", "901"]),
      evidence("text", "Volunteer chat reaction", "whether volunteers saw a plan change", "Identity and meaning", "A participant explains the account and what the reaction referenced", "the unexplained reaction icon did not identify the proposition acknowledged", "Capture the complete exchange and interview the reacting participant", "401")
    ]
  },
  {
    slug: "parade-balloon",
    claim: "A pear-shaped parade balloon drifted into a rooftop greenhouse during rehearsal. The greenhouse owner seeks repair costs, while the parade committee disputes how the balloon escaped and what damage witnesses actually observed.",
    disputedIssue: "What happened during the rehearsal, and which damage was caused by the balloon?",
    evidenceFocus: "Personal knowledge and lay testimony",
    ruleCard: {
      title: "A witness needs personal knowledge",
      plain: "A witness may testify about a matter only when the record supports that the witness personally perceived it. A lay opinion must also be based on that perception and help the factfinder.",
      simplified: "Seeing, hearing, or otherwise observing the event can supply personal knowledge. Repeating what someone else reported does not show that this witness perceived it.",
      rules: [RULES["602"], RULES["701"]]
    },
    paralegalPractice: "For every witness, record location, line of sight, timing, and exactly which facts the person perceived firsthand.",
    discussionQuestion: "Which follow-up questions would reveal whether a witness actually saw the balloon strike the greenhouse?",
    debrief: "Firsthand observations were useful; assumptions and repeated accounts were not. Lay impressions stayed within ordinary perception rather than technical causation.",
    examples: [0, 7],
    caseRoles: ["Rooftop gardener", "Parade volunteer", "Photograph source investigator", "Rehearsal coordinator", "Sketch source investigator", "Rooftop observer", "Tether handler", "Neighbor witness", "Wind-meter operator", "Greenhouse owner", "Glazier", "Teacher", "Pedestrian witness", "Balloon mechanic", "Parade marshal", "Glazier"],
    items: [
      evidence("transcript", "Rooftop gardener's statement", "the balloon's contact with the greenhouse", "Personal knowledge", "The gardener describes an unobstructed view from the roof", "the witness personally saw the contact from a clear nearby position", "Diagram the witness's position and record lighting and obstructions", "602"),
      evidence("note", "Volunteer's secondhand account", "how the tether came loose", "Lack of personal knowledge", "The volunteer must have perceived the release", "the volunteer arrived later and repeated what another person said", "Separate firsthand observations from information learned from others", "602"),
      evidence("photograph", "Undated damage photograph", "the broken greenhouse panel immediately afterward", "Photograph authentication", "No witness identifies when or where the image was made", "the image lacked a date and no witness connected it to the rehearsal damage", "Locate the source file and a witness who observed the depicted damage", "901"),
      evidence("recording", "Rehearsal coordinator's radio call", "the warning given before the drift", "Voice identification and perception", "A listener identifies the speaker and heard the call live", "the listener identified the voice and personally heard the warning", "Preserve surrounding radio traffic and prepare the identifying witness", "901"),
      evidence("map", "Unattributed vantage-point sketch", "where a witness stood during the event", "Personal knowledge foundation", "No witness identifies who drew the sketch or from what position", "the unexplained sketch could not show that its maker personally observed the event", "Identify the maker, date, and viewing position before proposing the sketch", "602"),
      evidence("note", "Rooftop observer's notes", "the sequence of the balloon's drift", "Personal knowledge", "The observer identifies notes made while watching from the adjacent roof", "the identified notes recorded events the witness personally observed as they occurred", "Preserve the full page and diagram the observer's line of sight", "602"),
      evidence("transcript", "Tether handler's deposition", "the condition of the knot before release", "Personal knowledge", "The handler explains personally tying and checking the knot", "the handler personally performed the task and described the observation", "Collect the full deposition designation and related exhibits", "602"),
      evidence("note", "Neighbor's wind conclusion", "the precise wind speed at roof height", "Improper lay opinion", "Reliable measurement or qualified expertise would be needed", "the neighbor guessed a technical measurement without an instrument or specialized basis", "Seek actual weather data rather than converting an impression into a precise measurement", "701"),
      evidence("spreadsheet", "Handheld wind-meter reading", "the measured wind speed beside the parade route", "Personal knowledge", "The operator identifies the device, time, location, and displayed reading", "the witness personally took and recorded the measurement; the ruling does not treat it as an expert causation opinion", "Preserve the device details and document where and when the reading was taken", "602"),
      evidence("recording", "Edited greenhouse video", "the sequence immediately after impact", "Personal knowledge and authentication", "The owner cannot explain a gap or produce the source recording", "the unexplained edit removed the relevant interval and left no adequate foundation for the offered sequence", "Request the original file and document every edit, pause, and timestamp", "901"),
      evidence("receipt", "Emergency glazing invoice", "the amount paid for immediate repairs", "Personal knowledge and damages", "The owner and glazier identify the work and invoice", "the witnesses connected the invoice to repairs they personally observed or performed", "Match each charge to photographs and the repair witness", "602"),
      evidence("note", "Secondhand classroom log", "a loud sound during rehearsal", "Personal knowledge", "The teacher was absent and copied a student's later account", "the teacher did not hear the sound and the entry merely repeated another person's report", "Interview the student who heard the sound and keep the accounts separate", "602"),
      evidence("transcript", "Distant pedestrian's conclusion", "that the committee was careless", "Lay opinion helpfulness", "The pedestrian must describe perceived facts rather than a legal conclusion", "the broad fault conclusion did not help explain any observed fact", "Prepare factual questions about what the witness saw and heard", "701"),
      evidence("photograph", "Mechanic's tether photograph", "the tether's appearance after recovery", "Personal knowledge and authentication", "The mechanic identifies recovering and photographing the tether", "the recovery witness connected the image to the actual tether", "Maintain the tether's custody log and the original image", ["602", "901"]),
      evidence("map", "Unissued route draft", "the intended rehearsal path", "Personal knowledge", "No witness identifies the draft as the plan used that day", "the preliminary route was not connected to the rehearsal and could not establish what participants personally followed", "Locate the issued route and its distribution list", "602"),
      evidence("voicemail", "Glazier's inspection voicemail", "the visible condition of the broken panel", "Personal knowledge and voice identification", "The glazier identifies the message and personal inspection", "the identified speaker described conditions personally observed during the repair visit", "Preserve the original voicemail and note the inspection date and speaker identity", ["602", "901"]),
    ]
  },
  {
    slug: "mosaic-bench",
    claim: "The library says a commissioned mosaic bench should have arrived as one finished piece. The artist says six sections were approved and seeks payment under the fabrication contract.",
    disputedIssue: "Did the delivered sections conform to the approved design and billing arrangement?",
    evidenceFocus: "Business records and proper foundation",
    ruleCard: {
      title: "Records of a regularly conducted activity",
      plain: "A business record may fit a hearsay exception when it was timely made by or from someone with knowledge, kept in a regularly conducted activity, and made as a regular practice.",
      simplified: "A custodian, qualified witness, or proper certification must establish those conditions, and untrustworthy circumstances can still defeat the exception. Creating a document for this lawsuit is not the same as routinely keeping it.",
      rules: [RULES["8036"]]
    },
    paralegalPractice: "Identify the record system, creator, timing, regular practice, and foundation witness or certification for each proposed business record.",
    discussionQuestion: "What questions should counsel ask a records custodian about the fabrication log?",
    debrief: "Routine, timely records with a qualified foundation differed from summaries assembled only for the dispute.",
    examples: [2, 8],
    caseRoles: ["Fabrication shop manager", "Supplier records custodian", "Library finance clerk", "Studio manager", "Shipping system custodian", "Kiln operator", "Delivery driver", "Contract signatory", "Warehouse records custodian", "Receiving clerk", "Courier records custodian", "Studio accountant", "Security system custodian", "Materials purchaser", "Library records manager", "Board secretary"],
    items: [
      evidence("spreadsheet", "Unexplained fabrication log", "when each bench section was produced", "Business-record foundation", "No custodian or certification explains when or how entries were made", "the proponent supplied no qualified foundation for the log's timing, source, or regular maintenance", "Identify a qualified witness or obtain a proper certification before listing the log", "8036"),
      evidence("receipt", "Stone supplier invoice", "materials purchased for six sections", "Business-record foundation", "The supplier custodian or certification establishes the record", "no witness or certification established how the invoice was made or kept", "Request a compliant certification or schedule the qualified custodian", "8036"),
      evidence("spreadsheet", "Library payment ledger", "payments issued under the commission", "Business-record foundation", "The finance clerk explains routine contemporaneous entries", "the ledger was routinely kept and timely entered by staff with knowledge", "Tie ledger entries to checks and prepare the finance clerk", "8036"),
      evidence("note", "Daily studio time ledger", "the fabrication hours recorded each workday", "Business-record foundation", "The studio manager explains contemporaneous entries made as a regular practice", "the qualified witness established that staff routinely recorded hours at the time of the work", "Preserve the complete ledger and prepare the studio manager", "8036"),
      evidence("email", "Automatic shipping confirmation", "when six crates left the shop", "Business record and authentication", "A shipping custodian explains the automated system", "the system foundation connected the routine notice to the shipment", "Preserve headers and obtain the carrier's system declaration", "8036"),
      evidence("spreadsheet", "Irregular kiln notes", "the temperatures used during fabrication", "Business-record foundation", "The entries were assembled from memory after several firings", "the notes were not shown to be timely records made as a regular practice", "Locate contemporaneous controller data or a qualified witness with a reliable record foundation", "8036"),
      evidence("receipt", "Recreated delivery ticket", "the condition at delivery", "Trustworthiness", "A delivery witness explains why and when it was recreated", "the ticket was reconstructed months later from memory after the dispute began", "Mark recreated documents and locate contemporaneous source material", "8036"),
      evidence("contract", "Commission payment schedule", "when installments became due", "Contract authentication", "The signers identify the executed agreement", "the signed schedule directly defined the parties' payment duties", "Compare signatures and attach the complete agreement", "901"),
      evidence("spreadsheet", "Crate-weight printout", "that the shipment contained six sections", "Business-record foundation", "No witness explains the database, scale, or handwritten overrides", "the unexplained overrides made the printout's source and trustworthiness uncertain", "Obtain the native entry, audit trail, and a qualified warehouse witness", "8036"),
      evidence("note", "Routine receiving tally", "the number of mosaic crates received", "Business-record foundation", "The receiving clerk explains contemporaneous tallies made for every delivery", "the clerk established that this tally was made on receipt as part of the library's regular practice", "Preserve the bound log and prepare the receiving clerk", "8036"),
      evidence("receipt", "Courier route manifest", "the delivery route and arrival", "Business-record foundation", "The courier custodian explains routine scanning and entries", "the manifest met the stated routine-record conditions", "Obtain certification and retain the complete route segment", "8036"),
      evidence("spreadsheet", "Artist's tax worksheet", "general annual studio expenses", "Relevance", "The accountant identifies the worksheet", "general annual expenses did not prove the cost or design of this bench", "Separate discoverable financial material from proposed trial exhibits", "401"),
      evidence("recording", "Shop security time-lapse", "assembly of separate bench sections", "System authentication", "The manager explains camera operation and export", "the system witness connected the recording to the relevant work period", "Preserve the native export and document camera timing", "901"),
      evidence("receipt", "Hardware store cash slip", "purchase of joining brackets", "Connection and foundation", "A buyer links the generic slip to this project", "no project code or witness connected the generic purchase to the bench", "Ask the purchaser to connect receipts to project records", "901"),
      evidence("spreadsheet", "Unverified exhibit inventory", "receipt of six labeled crates", "Business-record foundation", "No receiving witness or certification explains the entries", "the list was supplied without a witness, certification, or evidence of regular recordkeeping", "Locate the receiving clerk and the complete intake system export", "8036"),
      evidence("note", "Routine board minutes", "the design approval recorded at the monthly meeting", "Business-record foundation", "The secretary explains timely minutes kept for every meeting", "the secretary established that the minutes were recorded and maintained as a regular practice", "Preserve the approved minutes and prepare the secretary's foundation", "8036"),
    ]
  },
  {
    slug: "violet-awning",
    claim: "A cafe claims its fabricator installed a vivid violet awning instead of the approved muted plum. The fabricator argues that later negotiations resolved the color dispute and reduced the invoice.",
    disputedIssue: "Which color was authorized, and may settlement communications be used to prove liability or the claim amount?",
    evidenceFocus: "Compromise offers and settlement discussions",
    ruleCard: {
      title: "Compromise evidence has limited uses",
      plain: "Offers, consideration, and statements made during compromise negotiations generally may not be used to prove or disprove the validity or amount of a disputed claim, or for contradiction impeachment.",
      simplified: "The rule does not hide evidence that was otherwise discoverable merely because someone mentioned it during negotiations. A settlement communication may sometimes be admitted for another purpose, such as bias, but this case states the offered purpose for each item.",
      rules: [RULES["408"]]
    },
    paralegalPractice: "Separate underlying project evidence from compromise communications and label the purpose for which each proposed exhibit may be offered.",
    discussionQuestion: "Why does Rule 408 not make an otherwise discoverable color approval disappear?",
    debrief: "The court separated underlying project facts from statements and offers made to compromise the disputed claim.",
    examples: [1, 6],
    caseRoles: ["Cafe owner", "Fabricator", "Photograph witness", "Negotiation participant", "Supplier records custodian", "Settlement coordinator", "Scheduling witness", "Installer", "Negotiation participant", "Photograph source investigator", "Project witness", "Settlement estimator", "Cafe owner", "Installer", "Fabricator", "Negotiation participant"],
    items: [
      evidence("contract", "Signed color approval", "the authorized plum color", "Underlying relevant evidence and authentication", "The owner and fabricator identify the signed approval", "the signed approval existed before the dispute and directly addressed authorization", "Preserve the original and keep it separate from settlement correspondence", ["401", "901"]),
      evidence("email", "Offer to reduce the invoice", "that the fabricator admitted fault", "Prohibited compromise purpose", "The negotiation context identifies the disputed claim", "it was offered to prove liability from a compromise offer about the disputed claim", "Code settlement communications separately and flag Rule 408 before exhibit preparation", "408"),
      evidence("photograph", "Pre-installation fabric photo", "the selected swatch color", "Underlying evidence and authentication", "A witness identifies the swatch and photo date", "the authenticated image existed independently of settlement talks", "Retain the original file and connect it to the approved swatch number", ["401", "901"]),
      evidence("text", "Negotiation text saying 'our mistake'", "fault for the installed color", "Statement during compromise negotiations", "The thread shows it occurred while both sides disputed the claim", "the statement was offered to prove the disputed claim during compromise negotiations", "Preserve the thread but mark the trial-use issue for counsel", "408"),
      evidence("receipt", "Order from an unrelated job", "the color code ordered for this awning", "Relevance", "The supplier identifies a different project number on the order", "the order concerned another job and did not make authorization in this dispute more probable", "Match project numbers before adding vendor records to the exhibit list", "401"),
      evidence("email", "Settlement scheduling email", "the date the parties met", "Other purpose", "The participants identify the scheduling thread", "the limited timing purpose did not use the negotiation to prove liability or amount", "State the limited purpose clearly on the exhibit worksheet", "408"),
      evidence("email", "Settlement-session calendar invite", "why installation was delayed for one afternoon", "Other purpose", "The participants identify the invite and its date", "the court allowed the invite only to explain the scheduling delay, not to prove liability or claim value", "Record the limited timing purpose and omit negotiation terms", "408"),
      evidence("note", "Installer's pre-dispute work note", "the color code supplied to the crew", "Underlying evidence and authentication", "The installer identifies the contemporaneous note", "the authenticated work note predated and existed apart from negotiations", "Preserve the full notebook page and identify the installer", ["401", "901"]),
      evidence("recording", "Recorded settlement call", "that the owner exaggerated damages", "Compromise statement", "The participants identify the call and negotiation context", "the call was offered to attack the amount of the disputed claim using negotiation statements", "Segregate negotiation recordings and alert counsel before any use", "408"),
      evidence("photograph", "Color-shifted awning print", "the color actually installed", "Authentication and misleading presentation", "No source file or witness explains the print's altered color balance", "the unexplained color shift made the print unreliable for deciding the disputed shade", "Locate the original file and document lighting, display, and color adjustments", "901"),
      evidence("email", "Witness-benefit promise", "a project witness's possible bias", "Permitted other purpose", "The recipient identifies the message and the court limits its use", "the communication was admitted only to show possible witness bias, not to prove liability or claim value", "Redact negotiation details and state the permitted bias purpose", "408"),
      evidence("spreadsheet", "Settlement repair estimate", "the amount the fabricator should pay", "Compromise evidence", "The document was prepared and exchanged solely as part of compromise talks", "the estimate was offered to prove the amount of the disputed claim from the negotiations", "Keep the negotiation estimate separate from independent damages records", "408"),
      evidence("text", "Owner's text accepting delivery date", "when installation was scheduled", "Independent transactional statement and authentication", "The recipient identifies the pre-dispute thread", "the message concerned performance before any disputed claim or compromise negotiation", "Export the full pre-dispute thread with participant information", ["401", "901"]),
      evidence("note", "Pre-negotiation installation notes", "the color code the crew followed", "Underlying evidence and authentication", "The installer identifies contemporaneous notes made before the dispute", "the notes existed independently of compromise talks and directly addressed performance", "Preserve the complete notebook page and prepare the installer", ["401", "901"]),
      evidence("email", "Settlement replacement offer", "the amount the fabricator supposedly owed", "Compromise offer", "The thread shows the offer addressed the disputed claim", "the offer was used to prove the amount of the claim and therefore fell within the stated compromise restriction", "Flag the message as settlement material and keep it from the merits exhibit set", "408"),
      evidence("email", "Settlement promise to replace fabric", "that the fabricator admitted liability", "Compromise statement", "The participants identify the active negotiation context", "the promise was offered to prove liability from compromise negotiations", "Preserve it for the case file but mark the prohibited trial purpose", "408")
    ]
  },
  {
    slug: "paper-moon",
    claim: "A school theater loaned a silver paper moon to a bookstore for a reading event. The school seeks its return; the bookstore says an extension allowed it to keep the prop through autumn.",
    disputedIssue: "Did the school extend the loan, and what were the parties told about the return date?",
    evidenceFocus: "Hearsay and the purpose for which a statement is offered",
    ruleCard: {
      title: "Purpose matters for hearsay",
      plain: "Hearsay is an out-of-court statement offered to prove the truth of what it asserts. A statement offered for another relevant purpose may not be hearsay, though other objections may remain.",
      simplified: "The game will tell you the offered purpose. A message offered to show notice or that words of agreement were spoken is different from the same message offered to prove every factual assertion inside it.",
      rules: [RULES["801"]]
    },
    paralegalPractice: "For every statement, identify the speaker, recipient, exact words, and the specific purpose for which counsel plans to offer it.",
    discussionQuestion: "Could the same bookstore email be hearsay for one purpose but not hearsay for another? Explain the difference.",
    debrief: "The ruling turned on purpose. Some statements mattered because they gave notice or formed an agreement, not because every assertion was true.",
    examples: [0, 9],
    caseRoles: ["Email recipient", "Student messenger", "Bookstore manager", "Bookstore manager", "Loan-form custodian", "Event teacher", "Theater volunteer", "Recording source investigator", "School principal", "Bookstore manager", "Storage vendor custodian", "Calendar source investigator", "Bookstore manager deponent", "School email administrator", "Text-message recipient", "Book club member"],
    items: [
      evidence("email", "Unverified extension screenshot", "that words extending the loan were communicated", "Authentication before hearsay analysis", "No participant or account record identifies the screenshot", "even though contract-forming words may have legal significance, this screenshot lacked authentication", "Locate the complete thread and a participant before analyzing its offered purpose", "901"),
      evidence("note", "Student's notice note", "that the bookstore was told the school expected pickup", "Effect on recipient", "The student identifies delivering the note and the manager acknowledges receiving it", "the note was admitted to show notice to the bookstore, not to prove every statement in it", "Record who delivered and received the note and state the limited notice purpose", "801"),
      evidence("text", "Bookstore return reminder", "that the bookstore received notice of the requested date", "Effect on recipient", "The recipient identifies the message", "the message was offered to show notice to the recipient, not that every statement in it was true", "Document delivery, recipient identity, and the limited notice purpose", "801"),
      evidence("voicemail", "Manager's acknowledged voicemail", "why the bookstore delayed arranging pickup", "Effect on listener", "The manager identifies the caller's voice and the message received", "the authenticated message was offered to explain the manager's response, not to prove that an extension actually existed", "Preserve the original message and note the limited effect-on-listener purpose", "801"),
      evidence("contract", "Unverified prop-loan scan", "the initial return date", "Authentication", "No signer or custodian connects the scan to the executed agreement", "the writing's legal significance did not eliminate the separate need to authenticate this copy", "Locate the signed file or a witness who can identify the agreement", "901"),
      evidence("email", "Teacher's event instructions", "why the bookstore kept the moon on display", "Effect on recipient", "The recipient identifies the instruction email", "the instructions were relevant to explain the recipient's conduct whether or not every detail was true", "State the conduct-explanation purpose in the exhibit notes", "801"),
      evidence("note", "Volunteer's rumor list", "that everyone understood the loan was extended", "Hearsay", "The writer lists unnamed speakers", "the list repeated unverified assertions for their truth and identified no declarants", "Interview named sources separately instead of using a rumor compilation", "801"),
      evidence("recording", "Unidentified stage recording", "that attendees heard a fall-display announcement", "Authentication", "No witness identifies the event, speaker, or recording source", "a non-hearsay notice purpose did not cure the missing authentication foundation", "Identify the event, speaker, and source file before offering the recording", "901"),
      evidence("text", "Principal's question about pickup", "that the principal asked when pickup would occur", "Nonassertive communication", "The recipient authenticates the thread", "the question was not an assertion offered for its truth", "Capture the full exchange so punctuation and context are clear", "801"),
      evidence("email", "Bookstore claim that 'the moon is ours'", "that the bookstore owned the prop", "Hearsay truth purpose", "Authentication alone does not resolve hearsay", "the self-serving out-of-court assertion was offered to prove the ownership it asserted", "Separate authentication analysis from hearsay-purpose analysis", "801"),
      evidence("receipt", "Prop storage receipt", "that the bookstore paid to store the moon", "Circumstantial conduct", "The storage vendor identifies the transaction", "the conduct made continued possession more probable without relying on an out-of-court assertion", "Obtain vendor foundation and avoid overstating what payment proves", "401"),
      evidence("note", "Unattributed calendar screenshot", "the planner's intended pickup date", "Authentication and state of mind", "No owner identifies the calendar, account, or entry date", "the possible state-of-mind purpose did not cure the absence of authentication or timing foundation", "Identify the calendar owner and preserve the native entry with metadata", "901"),
      evidence("transcript", "Manager's deposition on notice", "that the manager received the school's pickup demand", "Effect on recipient", "The certified testimony recounts the manager's own receipt of the demand", "the testimony was admitted for the limited purpose of notice, not to prove every assertion in the demand", "Designate the complete question and answer and label the offered purpose", "801"),
      evidence("email", "Read-receipt notification", "that the extension request reached the school account", "Effect and system evidence", "The email system process is authenticated", "the system notice supported receipt rather than the truth of the request's contents", "Preserve headers and document how the read-receipt system works", "801"),
      evidence("text", "Cropped 'keep it up' screenshot", "that the recipient was instructed to leave the prop displayed", "Authentication", "The crop omits the account, date, and surrounding thread", "the instruction may be nonassertive, but this image was not authenticated as the manager's message", "Obtain the complete thread and a participant who can identify it", "901"),
      evidence("note", "Book club member's summary", "that the school promised a fall loan", "Hearsay summary", "The member did not hear the alleged promise", "the summary repeated a statement the member learned from someone else and was offered for its truth", "Find the person who heard the original words and document each layer", "801")
    ]
  },
  {
    slug: "rooftop-bees",
    claim: "Tenants seek return of a decorative bee hotel moved during roof repairs. The building owner says the move became permanent because wind exposure made the original location unsafe.",
    disputedIssue: "Was the bee hotel moved temporarily, and what expertise is needed to assess the rooftop location?",
    evidenceFocus: "Lay opinions and expert opinions",
    ruleCard: {
      title: "Lay and expert opinions do different work",
      plain: "A lay opinion must be based on the witness's perception, help with a fact, and avoid specialized knowledge. Expert testimony may address specialized matters when the witness is qualified and the Pennsylvania requirements are met.",
      simplified: "A tenant may describe a structure as wobbling after seeing it move. Technical claims about wind loads or structural safety require an appropriate expert foundation in this case.",
      rules: [RULES["701"], RULES["702"]]
    },
    paralegalPractice: "Separate firsthand observations from specialized conclusions, collect expert qualifications, and organize the materials each expert relied on.",
    discussionQuestion: "Where is the line between saying the bee hotel looked unstable and giving a structural-safety opinion?",
    debrief: "Ordinary observations stayed with lay witnesses. Specialized wind and anchoring conclusions required a qualified expert and an accepted methodology.",
    examples: [0, 6],
    caseRoles: ["Tenant witness", "Structural engineer", "Photograph source investigator", "Project architect", "Cafe owner witness", "Dog walker witness", "Model source investigator", "Neighbor witness", "Property owner", "Maintenance worker", "Pollinator expert", "Records clerk witness", "Diagram source investigator", "Project architect", "Roof contractor", "Recording source investigator"],
    items: [
      evidence("note", "Tenant's wobbling description", "visible movement during a storm", "Lay opinion", "The tenant describes watching the structure move", "the ordinary description was based on perception and helped explain the observed condition", "Record the witness's location, weather, and concrete observations", "701"),
      evidence("spreadsheet", "Engineer's anchor calculation", "the force acting on the structure", "Specialized opinion", "A qualified structural engineer explains the inputs and generally accepted method", "the qualified expert used an explained methodology relevant to the rooftop conditions", "Collect the expert's qualifications, inputs, and calculation file", "702"),
      evidence("photograph", "Undated anchor photo", "the anchoring method before removal", "Authentication", "No witness identifies the roof, date, or photographer", "the image was not connected to this roof or the relevant time", "Locate the source file and a witness who observed the depicted anchors", "901"),
      evidence("transcript", "Architect's structural opinion", "whether the original location was suitable", "Expert qualification", "The architect's training and experience address rooftop loads", "the qualified witness used specialized knowledge helpful to the location dispute", "Collect the CV, report, plans reviewed, and testimony outline", "702"),
      evidence("note", "Cafe owner's 'unsafe' comment", "that the structure violated engineering standards", "Improper lay opinion", "The witness may describe observations but lacks the technical basis asserted", "the bare safety conclusion depended on specialized knowledge not supplied", "Reframe the interview around observed movement, sounds, and conditions", "701"),
      evidence("map", "Dog walker's safety conclusion", "that the original roof position violated structural standards", "Improper lay opinion", "The witness saw the location but lacks a technical basis for code compliance", "the specialized safety conclusion went beyond the witness's ordinary perception", "Use the witness for location observations and reserve structural conclusions for a qualified expert", "701"),
      evidence("spreadsheet", "Unexplained wind model", "expected loads at both roof positions", "Expert methodology", "No qualified witness explains the inputs or method", "the technical output lacked a qualified sponsor and an explained generally accepted methodology", "Obtain the native model, inputs, validation, and an appropriate expert", "702"),
      evidence("recording", "Neighbor's humming observation", "whether bees used the structure", "Lay perception", "The neighbor describes proximity and repeated listening", "the witness's ordinary sensory observation was helpful and firsthand", "Record distance, dates, and conditions affecting the observation", "701"),
      evidence("note", "Safety blog shown to the owner", "why the owner ordered a temporary move", "Effect on listener", "The owner identifies reading the post before giving the order", "the post was admitted only to explain the owner's decision, not as expert proof that the structure was unsafe", "Preserve the page and date, and state the limited notice purpose", "801"),
      evidence("photograph", "Unverified level photo", "that the base appeared tilted", "Authentication", "No witness explains where or how the level was placed", "without a source or placement foundation, the image could mislead rather than support a lay observation", "Identify the photographer and document how the level was positioned", "901"),
      evidence("transcript", "Botanist's bee-use opinion", "whether relocating the hotel affected nesting", "Expert qualification and helpfulness", "The botanist's specialized experience concerns pollinator nesting", "the qualified opinion addressed a specialized issue beyond ordinary knowledge", "Collect qualifications and the observations or literature supporting the opinion", "702"),
      evidence("note", "Records clerk's 'very windy' description", "ordinary weather conditions the clerk personally felt", "Lay opinion", "The clerk describes being on the roof and the effects personally observed", "the ordinary impression was based on perception and did not claim a precise technical measurement", "Record the concrete observations supporting the lay description", "701"),
      evidence("map", "Secondhand relocation diagram", "the route and final placement", "Personal knowledge", "The clerk drew it from an unidentified account and never saw the move", "the diagram was not based on the witness's own perception", "Interview the people who directed or observed the move", "602"),
      evidence("spreadsheet", "Architect's unexplained model output", "that one location was safer", "Expert methodology", "The architect must explain inputs and accepted method", "the unexplained output did not show a generally accepted methodology", "Request native model files, inputs, method, and validation material", "702"),
      evidence("object", "Corroded mounting bracket", "the condition of the original hardware", "Lay and expert boundary", "The remover identifies the bracket; an expert addresses failure mechanism", "the witness identified the actual bracket and the court limited lay testimony to visible condition", "Maintain custody and separate identification testimony from expert conclusions", "701"),
      evidence("recording", "Unverified roof walkthrough", "the observable conditions before relocation", "Authentication", "No witness identifies the date, roof, or speaker", "the recording lacked the basic identity and timing foundation needed to connect it to this dispute", "Locate the original recording and an identifying witness", "901")
    ]
  },
  {
    slug: "brass-octopus",
    claim: "A seafood cafe and a maritime club each claim a brass octopus centerpiece. Before trial, both sides ask the court to limit confusing exhibits about unrelated antiques and prior negotiations.",
    disputedIssue: "Which transaction controls ownership, and which proposed exhibits will help rather than confuse the factfinder?",
    evidenceFocus: "Motions in limine, relevance, and unfair prejudice or confusion",
    ruleCard: {
      title: "Relevant evidence can still be limited",
      plain: "Relevant evidence tends to make an important fact more or less probable. A Pennsylvania court may still exclude it when its probative value is outweighed by unfair prejudice, confusion, misleading the jury, delay, wasted time, or needless cumulative proof.",
      simplified: "The pretrial motion in limine identifies the purpose and objection before the exhibit reaches the factfinder. In this case, dramatic or repetitive material is not automatically useful merely because it mentions the octopus.",
      rules: [RULES["401"], RULES["403"]]
    },
    paralegalPractice: "Build an exhibit chart with offered purpose, objection, response, ruling, redactions, and the final exhibit number used at trial.",
    discussionQuestion: "What information would counsel need before asking to exclude an exhibit as confusing or needlessly cumulative?",
    debrief: "The court admitted focused proof of the disputed transaction and limited material that invited confusion, improper decision-making, or repetitive presentation.",
    examples: [2, 12],
    caseRoles: ["Cafe purchaser", "Club records custodian", "Pickup witness", "Gallery curator", "Email recipient", "Delivery driver", "Metal restorer", "Club event videographer", "Object maker", "Transaction email recipient", "Route-map source investigator", "Text-message participant", "Litigation paralegal", "Photographer", "Seller deponent", "Demonstrative witness"],
    items: [
      evidence("contract", "Unsigned cafe agreement", "the cafe's claimed ownership", "Relevance and authentication", "No signer identifies the incomplete draft as the parties' agreement", "the unsigned, incomplete draft was not connected to an executed transaction", "Locate the final version and a signer or custodian who can identify it", "901"),
      evidence("contract", "Unverified club loan form", "the club's claim that the octopus was only loaned", "Authentication", "No custodian or signer identifies the copy", "the proponent did not authenticate the form as the operative loan record", "Compare versions and identify a signer or records witness", "901"),
      evidence("photograph", "Pickup-day photograph", "who possessed the centerpiece after the transaction", "Relevance and authentication", "A present witness identifies the date and people", "the identified photograph provided focused circumstantial proof of possession", "Preserve the original file and prepare the observing witness", ["401", "901"]),
      evidence("photograph", "Gallery of twenty similar octopuses", "that brass octopuses are commonly sold", "Confusion and cumulative evidence", "A curator could identify the images", "the large gallery added little to this transaction and risked distracting from the particular item", "Narrow demonstratives to the few images that serve a stated purpose", "403"),
      evidence("email", "Cafe pickup confirmation", "the agreed pickup date and item", "Relevance and authentication", "The recipient identifies the thread", "the authenticated message directly concerned performance of the disputed transaction", "Preserve the native email and cross-reference the bill of sale", ["401", "901"]),
      evidence("note", "Pickup condition checklist", "the centerpiece's condition and item number at transfer", "Relevance and authentication", "The driver identifies the checklist completed during pickup", "the focused record helped identify the item and condition at the disputed transfer", "Match the item number to the object and prepare the driver", ["401", "901"]),
      evidence("receipt", "Metal-restoration invoice", "the club's spending on the centerpiece", "Relevance", "The restorer identifies the work and item", "the expense was circumstantial evidence of the club's treatment of the item", "Link the serial description to the object and damages theory", "401"),
      evidence("recording", "Three-hour club banquet video", "that the octopus appeared at club events", "Waste of time and cumulative proof", "A witness identifies the recording", "hours of repetitive footage had minimal added value beyond a short authenticated clip", "Create a precise clip log and ask counsel whether a stipulation will suffice", "403"),
      evidence("object", "Engraved brass base", "the identity and dedication of the particular centerpiece", "Relevance and authentication", "The maker identifies the engraving and object", "the distinctive engraving connected the object to the transaction history", "Photograph all sides and maintain the object's custody and exhibit number", ["401", "901"]),
      evidence("email", "Seller's item-number email", "which buyer was assigned the octopus's inventory number", "Relevance and authentication", "The recipient identifies the complete transaction thread", "the authenticated message directly linked the disputed item number to the transaction", "Preserve headers and cross-reference the inventory and pickup records", ["401", "901"]),
      evidence("map", "Unverified pickup route", "the sequence of cafe and club stops", "Authentication", "No driver or source record supports the annotations", "the unexplained map was not connected to the actual pickup route", "Identify the mapmaker and compare annotations with route records", "901"),
      evidence("text", "Repeated screenshots of the same pickup text", "that pickup was scheduled", "Cumulative evidence", "Participants identify the same underlying message", "multiple copies needlessly repeated a fact already shown by the complete authenticated thread", "Deduplicate exhibits and preserve one best-quality authenticated version", "403"),
      evidence("contract", "Draft motion-in-limine exhibit list", "ownership of the centerpiece", "Relevance", "The filing record identifies it only as counsel's preliminary tracking chart", "the procedural draft did not prove ownership and was kept from the trial record", "Maintain the chart for case management but do not place it in the jury exhibit set", "401"),
      evidence("photograph", "Condition photo with disclosed crop", "the visible condition of the centerpiece", "Fair presentation", "The photographer supplies the original and explains the crop", "the focused image served a limited illustrative purpose because the original and edit disclosure prevented confusion", "Retain both versions and label the crop as a demonstrative", "403"),
      evidence("transcript", "Incomplete deposition excerpt", "which buyer the seller intended to contract with", "Completeness and confusion", "The excerpt omits the question and the witness's qualification", "the incomplete segment risked misleading the factfinder about the seller's answer", "Include the full question, answer, objections, and necessary surrounding pages", "403"),
      evidence("object", "Disclosed scale model", "the shape and location of identifying engravings", "Helpful demonstrative", "A witness explains the accurate scale and limited purpose", "the neutral, accurately scaled model helped orient the factfinder without exaggeration", "Verify scale, label it as a demonstrative, and preserve the actual object's photographs", "403")
    ]
  }
];

export const CASE_INSTRUCTION = RAW_CASE_INSTRUCTION.map(({ caseRoles, ...caseData }) => ({
  ...caseData,
  items: caseData.items.map((item, index) => ({ ...item, caseRole: caseRoles[index] }))
}));
